### ISSUE TITLE
Sort tables?

### ISSUE THREAD

**Issue by toqduj** [nicolaskruchten/jupyter_pivottablejs#10]
pivottables already has excellent filtering abilities, but would it be possible to sort the resulting items in the table by clicking on their column headers?

**Comment by nicolaskruchten** [comment]
This is fairly hard to implement, but it's a good idea! See related FAQ entry for the underlying PivotTable.js library: https://github.com/nicolaskruchten/pivottable/wiki/Frequently-Asked-Questions#sorting-in-built-in-table-renderer

**Comment by toqduj** [comment]
Sorry about missing the FAQ. Will look into the 3rd party wrapper, but am a bit worried about that wrapper's future and mentions of .Net.... :)

Thanks for the very nice package, though! It has certainly helped me "sell" the idea of a more database-y system for our measurement and sample registration!

**Comment by nicolaskruchten** [comment]
Happy to help! I really should find the time to bake this sorting feature into the default renderer, but life keeps getting in the way :)
