### ISSUE TITLE
Set output table encoding

### ISSUE THREAD

**Issue by toqduj** [nicolaskruchten/jupyter_pivottablejs#11]
For a quick-and-dirty database, I am using the table generated by pivottablejs directly in other browsers. However, the encoding is not set, leading to misformatting of the table values. 

It would be splendid if the output table html file could have this just behind the <head> tag:
<meta charset="UTF-8">

Cheers, 

Brian.

**Comment by nicolaskruchten** [comment]
Hi Brian,

The tag you posted didn't come through... Can you edit your issue please so I have a better idea of what you are proposing?

Thanks,
Nicolas

**Comment by toqduj** [comment]
Ah, that didn't indeed. It's the [left angle bracket] meta charset="UTF-8" [right angle bracket] tag. In my tests of adding that to the html file output by pivot_ui, it solves the encoding issue in browsers.

**Comment by nicolaskruchten** [comment]
Long time to get this fix in but I've just done it and released version 0.3.0 :)

**Comment by toqduj** [comment]
Awesome, thanks!
