### ISSUE TITLE
data is not being updated in pivot table

### ISSUE THREAD

**Issue by hojene007** [nicolaskruchten/jupyter_pivottablejs#12]
Hello!

First of all thank you for making this, excellent tool and super useful! I have been using the pivottablejs app for a couple of months and it has been working fine for me... i have multiple pivottables in my jupyter notebook with different data inputs which seemed to work.

Recently however, i have been having a problem where the data in the pivottable does not change regardless of the pandas dataframe reference that i am using... it displays results related to an old pandas dataframe, i was using earlier, that is not even a part of the current notebook.. 

the pivottablejs.html is not updating either and is stuck on the old data ... how would i go about fixing this? (re-installing pivotttablejs did not help :))

thank you in advance!

**Comment by nicolaskruchten** [comment]
There is a known issue with this system whereby when you change Notebook directories, either via code or configuration, the file doesn't get written in the correct place. Normally this manifests as a 404 error but if you had already written a file, then the symptom would be that the old file is being served up.

If you use the `outfile_path` parameter set to `test.html`, do you get a 404 error?

**Comment by hojene007** [comment]
yep this is exactly what happens...

**Comment by hojene007** [comment]
ahh.. it saves it in the re-specified destination path...got it thanks you!!
