### ISSUE TITLE
outfile_path completely different from url to access IFrame

### ISSUE THREAD

**Issue by douglascamata** [nicolaskruchten/jupyter_pivottablejs#13]
Hello, in the company I work for we have a very specific kernel for Jupyter with a very different architecture. We need to pass a full path in `outfile_path` , something like: `/folder1/another_folder/notebooks/frame.html`. But the  file is served at `<jupyter_url>/notebooks/frame.html`. What you think about adding a `web_path` parameter to `pivot_uid` to be able to handle these cases? The default value can be equal to `outfile_path`. I already have the patch ready to open a pull request if you like the idea.

**Comment by nicolaskruchten** [comment]
I'd be open to that pull-request, if the default value of `web_path` was backwards-compatible :)

**Comment by nicolaskruchten** [comment]
You can just provide an absolute path for `outfile_path`, no?

**Comment by nicolaskruchten** [comment]
To answer my own question: clearly not! Reopening :)

**Comment by nicolaskruchten** [comment]
This is now addressed via the `url_prefix` parameter.
