### ISSUE TITLE
Filter when "too many to list"

### ISSUE THREAD

**Issue by jonathanherr** [nicolaskruchten/jupyter_pivottablejs#17]
Is it possible to turn on the filtering textbox when a field returns the 'too many to list' error? Perhaps there are too many to list, but if you could enter a string, you could filter anyway. Alternatively, is the max value for the list size accessible somewhere for user editing?

**Comment by nicolaskruchten** [comment]
There is no way to pass PivotTable.js options from Python via this little plugin, but if there was, the underlying option would be `menuLimit` ( see https://github.com/nicolaskruchten/pivottable/wiki/Parameters )

**Comment by nicolaskruchten** [comment]
You can now pass in extra kwargs to `pivot_ui` including `menuLimit`.
