### ISSUE TITLE
Whats wrong with this!!

### ISSUE THREAD

**Issue by HannahJSwystun** [nicolaskruchten/jupyter_pivottablejs#20]
Hi,
I would like to simply display col row val and it does not work :

<script type="text/javascript">    
    $(function(){

        $("#output").pivot(
            [
                {Analysis: "A1", Parameters: "P1", value: "0.25"},
                {Analysis: "A1", Parameters: "P2", value: "1.65"},
                {Analysis: "A1", Parameters: "P2", value: "3.95"}
            ],
            {
                rows: ["Analysis"],
                cols: ["Parameters"],
                vals: ["value"]
            }
        );
     });
</script>

        

<div id="output" style="margin: 30px;"></div>

Did i miss something please ?

**Comment by nicolaskruchten** [comment]
This issue doesn't seem to pertain to the current repo, which is the Jupyter integration for PivotTable.js ... Please repost it to the appropriate repo here: https://github.com/nicolaskruchten/pivottable/issues/new
