### ISSUE TITLE
Emergent - rework to use Apache Arrow for I/O

### ISSUE THREAD

**Issue by rickFanta** [nicolaskruchten/jupyter_pivottablejs#21]
Hiya Nicolas,

This doesn't really belong as an issue but is more of an FYI that you might be interested in.

As cool as the current implementation is, writing all the data to an html file just doesn't work well, esp. when datasets get large.  [I found the old issues where you discussed and then eventually rejected alternative server side implementations to avoid overcomplicating the codebase.]

Apache Arrow (and Feather files) is an emergent technology that works well with pandas and might help speed the client-side performance.  FYI, (if you're interested), there is currently a Jira open to do a Javascript implementation of Arrow using Typesciprt + Flatbuffers.  https://issues.apache.org/jira/browse/ARROW-541

[Since that impl;ementation doesn't exist yet, it's kinda silly to file this as a Jira, but perhaps this is a placeholder.]

Separately, as an alternative to this conda/python project, have you ever embedded pivottable.js directly in a Jupyter (or perhaps Zepplin or Beaker) notebook?  I can share this if I get it going but if you have something already I'd love to see it.

Best,
Rick

**Comment by nicolaskruchten** [comment]
So PivotTable.js works very well with CSV files already, and these new file-formats are exciting to me in the context of that library mostly in that they are binary therefore smaller than CSV files, and hence will transfer from server to client more quickly.

In the context of the Jupyter integration, certainly there are better options than embedding the CSV directly in the HTML but this seemed to me the most expedient way to get this thing available within Jupyter. I've not tried other notebook systems as I'm not a user of any of them, and at the moment most of their extension APIs are either too hard to use or too unstable to be worth my time :)
