### ISSUE TITLE
Easily add a custom aggregator to the jupyter pivot table

### ISSUE THREAD

**Issue by rickFanta** [nicolaskruchten/jupyter_pivottablejs#22]
Hiya,

It could easily be that I'm missing something, but I don't immediately see how to add custom aggregators to the Jupyter pivot table implementation without changing the javascript + html source in jupyter_pivottablejs-master/pivottablejs/__init__.py and redeploying the packing to python/pip/conda.

Ideally, it would be great if you could pass the custom aggregator(s) + sorters, etc to the javascript via the Python module.  [That might make the code a bit uglier (and in the worst case require the use of "eval" or similar), but it would be useful and avoid the need to tailor the Javacript and modules for every purpose that you might want across projects.]

Thank again for your time and effort,
Rick

**Comment by nicolaskruchten** [comment]
Indeed, it's not possible to add custom aggregators via the current integration... It feels very un-Pythonic to have an API where one specifies things via Javascript strings so I never pursued that avenue.

**Comment by rickFanta** [comment]
Very true (albeit I'm not a purist and can live with a few wrinkles).  

Will look further into making a notebook that uses your javascript pivot table component directly.  That might be cleaner.

**Comment by rickFanta** [comment]
[Please feel free to close as it suits you.]
