### ISSUE TITLE
My Jupyter document does not have the sort arrows on the bar chart

### ISSUE THREAD

**Issue by y2kbowen** [nicolaskruchten/jupyter_pivottablejs#24]
I am using the jupyter_pivottablejs on my document and following along with the examples, but my notebook does not render the sort arrows like the examples. Am I missing something?
![missingsortarrows](https://cloud.githubusercontent.com/assets/4991352/25204694/66b61ce4-2524-11e7-9508-2acc7e5ba98d.PNG)

I was looking for the arrows like the picture below:
![sortarrowsexpected](https://cloud.githubusercontent.com/assets/4991352/25204759/a5889b04-2524-11e7-80cf-93fc5eb04369.PNG)

**Comment by nicolaskruchten** [comment]
Ah yes, `jupyter_pivottable` uses version 1.6.3 of PivotTable.js, but the sorting UI was introduced in 2.11 so I will need to update `jupyter_pivottable`. I'll try to do this in the next couple of days.

**Comment by y2kbowen** [comment]
Is all that needs to be done is change the version numbers in these script links or do other links in the template need updates as well?

For example:

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/pivot.min.js"></script>`

And replace like this

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/2.11.0/pivot.min.js"></script>`


And the same for these:

`
src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/pivot.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/d3_renderers.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/c3_renderers.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pivottable/1.6.3/export_renderers.min.js"></script>
`

**Comment by nicolaskruchten** [comment]
It's something like that, yep :)

**Comment by nicolaskruchten** [comment]
Sorry for the delay on this, but I've just pushed a new version of this package to PyPi so you should be able to reinstall it with `pip install pivottablejs` and get the features you're looking for. You'll also get some new aggregators like Median and Sample Variance, which is what I was waiting to finish before pushing this new version :)
