### ISSUE TITLE
Moved from pivottable issue#739 

### ISSUE THREAD

**Issue by zpencerguy** [nicolaskruchten/jupyter_pivottablejs#27]
@nicolaskruchten to install in Azure I used !pip install pivottablejs directly in the notbook, then import pivottablejs.

**Comment by zpencerguy** [comment]
After digging around Azure's site I found the fix (https://notebooks.azure.com/Microsoft/libraries/nbextensions/html/InstallExtension.ipynb).

Code to enable notebook extensions & install JavaScript:
!pip install jupyter_contrib_nbextensions
!jupyter contrib nbextension install --user

**Comment by nicolaskruchten** [comment]
Ah, I'm glad you resolved this! Sorry I dropped off there, it's been a busy summer :(
