### ISSUE TITLE
Pivottable.js Installation

### ISSUE THREAD

**Issue by Mattin30** [nicolaskruchten/jupyter_pivottablejs#28]
Can you please provide a visual installation of pivottable? I am not very familiar with the coding. I would like to install it on  Easyphp server on my computer. I went through your documentation, and made some internet search but I couldn't find visual installation guides. Thanks.

**Comment by nicolaskruchten** [comment]
I'm not sure what you mean... ?

**Comment by Mattin30** [comment]
Is there a youtube video for example showing the installation of pivottable.js? I would like to use pivottable.js. I have a webserver (Easyphp) on my computer. I couldn't figure out the installation process. I am not a developer.

**Comment by nicolaskruchten** [comment]
Ah ok. If you're not a developer you're not going to be able to use this library, as it's not a full UI, it's a library for developers to use to contruct one.

You can use this page to do some quick data analysis in your browser without installing anything, though: https://pivottable.js.org/examples/local.html :)

**Comment by Mattin30** [comment]
Ok, thanks. I will try the link. I hope you do a full UI version too. It seems very nice and useful.
