### ISSUE TITLE
How to specify the value and aggregator

### ISSUE THREAD

**Issue by stumitchell** [nicolaskruchten/jupyter_pivottablejs#29]
I can specify what the rows and columns in my dataset
    from pivottablejs import pivot_ui
    pivot_ui(prog_df, 
         rows = ['spot_type'],
         cols = ['group', 'daypart', 'station'],
         vals = ['tarp'])

but how do I tell it I want the value of the cells to be the sum of the tarp

**Comment by nicolaskruchten** [comment]
add `aggregatorName = 'Sum'` :) ... reference here: https://github.com/nicolaskruchten/pivottable/wiki/Parameters#options-object-for-pivotui

**Comment by stumitchell** [comment]
Great thanks!
