### ISSUE TITLE
def pivot_ui() accepts no kwargs

### ISSUE THREAD

**Issue by karlanka** [nicolaskruchten/jupyter_pivottablejs#35]
Following  [this example](https://github.com/nicolaskruchten/jupyter_pivottablejs/blob/master/example/jupyter_pivottablejs_example.ipynb
)
yields this error message:
`TypeError: pivot_ui() got an unexpected keyword argument 'rows'`

The function in `pivottablejs.py` installed with `conda install pivottablejs` looks like this:
```
def pivot_ui(df, outfile_path = "pivottablejs.html", width="100%", height="500"):
    # FIXME: we shouldn't hard-code the port here
    port = 8888 # get_config().NotebookApp.port
    static_path = 'http://localhost:%s' % port
    with open(outfile_path, 'w') as outfile:
        outfile.write(template % {'div': df.to_csv(),
                                  'static': '%s/static' % static_path})
    return IFrame(src=outfile_path, width=width, height=height)

```

Aren't this function missing the **kwargs? It doesn't seem like this is wahat have been installed. https://github.com/nicolaskruchten/jupyter_pivottablejs/blob/master/pivottablejs/__init__.py

**Comment by nicolaskruchten** [comment]
Unfortunately, you cannot install this module using `conda`, only `pip`, as someone else has squatted the `pivottablejs` name on Conda with an incompatible older version :(

See https://github.com/ContinuumIO/pivottablejs-airgap/issues/3 and vote there to let them know the confusion is hurting users please!

**Comment by nicolaskruchten** [comment]
I've just edited the README to hopefully save everyone some time in the future. Sorry for the confusion...
