### ISSUE TITLE
There is no option to control the type of graphs that can be generated for the data

### ISSUE THREAD

**Issue by vishnuragas** [nicolaskruchten/jupyter_pivottablejs#36]
User cannot choose the type of graphs that needs to be generated. Say, only bar graphs and tree map is needed, the user cannot choose and still has to display all other options even though not used.

**Comment by nicolaskruchten** [comment]
That's correct, at the moment this is not possible to do via the Python wrapper around this Javascript library...

**Comment by supernooba** [comment]
Hi, I followed the documentation but I cant plot the graph using plotly. Any suggestion? thanks a lot

**Comment by nicolaskruchten** [comment]
@supernooba Plotly is not supported in this Jupyter wrapper yet, sorry!

**Comment by supernooba** [comment]
@nicolaskruchten thank you very much for the reply
