### ISSUE TITLE
No Module Found

### ISSUE THREAD

**Issue by sobolev** [nicolaskruchten/jupyter_pivottablejs#37]
Perhaps something silly on my part but I installed from conda first, realized that was wrong way to do it. Uninstalled and then redid with PIP. Now when I try to import from Jupyter I get the following error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-66290362da33> in <module>()
----> 1 import pivottablejs as ptjs

ModuleNotFoundError: No module named 'pivottablejs'

**Comment by sobolev** [comment]
resolved. looked at my sys.path. pointing in the wrong place for some reason.

**Comment by nicolaskruchten** [comment]
ok!
