### ISSUE TITLE
Apply filter by defaul

### ISSUE THREAD

**Issue by jorgelaranjo** [nicolaskruchten/jupyter_pivottablejs#39]
Is there any way to apply the 'filter' from PivotTableJs directly on Python, eg, have a bunch of data but by default apply a filter to it, so that all data is available but only some is on display by default?

**Comment by jorgelaranjo** [comment]
@nicolaskruchten 
Thanks. But not clear how the ``pivot_ui`` ``filter`` passes the item implicitly to the function

`
def foo_bar_func(list):
    if(df.Col6.isin(list)): return True #Cannot be df, needs to be the item from pivot_ui
    else: return False

pivot_ui(df, 
         cols =['Col1'],
         rows=['Col2','Col3','Col4', 'Col5'], 
         vals=['Col6'],
         rendererName = 'Table',
         aggregatorName = 'Sum',
         filter = foo_bar_func([1,2,3]) #how is the item passed to the function?
        )
`

**Comment by nicolaskruchten** [comment]
You need to use `inclusions` and `exclusions`, not `filter` :)

**Comment by jorgelaranjo** [comment]
👍 That explains it :) Works well now :)

**Comment by nicolaskruchten** [comment]
Glad this works now. Github Issues is actually my preferred way of doing things: I have a good workflow for managing Github notifications and it leaves a trail of hints for other people who have similar questions in the future. As a result, I refuse to deal with this kind of thing via private email. You can try your luck on StackOverflow, and I occasionally glance there but my goal is for the Issues here to be an accumulation of all knowledge/conversation about this project :)
