### ISSUE TITLE
Add MyBinder support

### ISSUE THREAD

**Issue by psychemedia** [nicolaskruchten/jupyter_pivottablejs#46]
Hi
If you add a `requirements.txt` file containing `pandas` and a button to the README along the lines of:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nicolaskruchten/jupyter_pivottablejs/master?filepath=%2Fexample%2Fjupyter_pivottablejs_example.ipynb)

or share [this link](https://mybinder.org/v2/gh/nicolaskruchten/jupyter_pivottablejs/master?filepath=%2Fexample%2Fjupyter_pivottablejs_example.ipynb), folk can try out the demo notebook interactively direct from their browser and without having to install anything.

**Comment by nicolaskruchten** [comment]
Cool! I'd happily merge a PR if you have one :)
