### ISSUE TITLE
Change location where pivottablejs.html is created

### ISSUE THREAD

**Issue by Joehurley** [nicolaskruchten/jupyter_pivottablejs#5]
It appears that the package writes the pivottablejs.html file to the "root" ipython directory. In order for this to work, I have to move this file to my notebook directory (I created a sub folder under "root" called 'notebooks'). Is there a config setting to change where this file is created?

**Comment by nicolaskruchten** [comment]
You can just provide an absolute path for `outfile_path`, no?

**Comment by nicolaskruchten** [comment]
(self-reply: no)

**Comment by nicolaskruchten** [comment]
This is now addressed via the `url_prefix` parameter.
