### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by mattmezs** [nicolaskruchten/jupyter_pivottablejs#50]
I am new to Javascript, jquery and the rest. I am having trouble getting restore functionality working with the pivottable. That is, I cannot restore the configuration saved to cookies. 

			<button id="restore" onclick="restore">res</button>
				<div id="output" style="height:100px;width:100px;margin-left:20px;transform:scale(.7);"></div>
				
				<script>  
			  

						$(function() {
								$("#output").pivotUI({{content[2]|safe}},
									{
									
										rows: ['Program'],
										cols: ['Milestone'],
										vals: ['Amount'],
										aggregatorName: "Sum",
										renderers: $.extend(
											$.pivotUtilities.renderers, 
											$.pivotUtilities.plotly_renderers
										),
										onRefresh: function(config) {
											var config_copy = JSON.parse(JSON.stringify(config));
											//delete some values which are functions
											delete config_copy["aggregators"];
											delete config_copy["renderers"];
											//delete some bulky default values
											delete config_copy["rendererOptions"];
											delete config_copy["localeStrings"];
											$.cookie("pivotConfig", JSON.stringify(config_copy));
										}
									});
									    $("#restore").on("click", function(){
										$("#output").pivotUI(mps, JSON.parse($.cookie("pivotConfig")), true);
									});
							 });

**Comment by mattmezs** [comment]
in the above code, mps under the restore function is actually the correct source

**Comment by nicolaskruchten** [comment]
I assume that this is with respect to pivottable.js and not the Jupyter version, right? If so, could you please close this issue and post a new one at https://github.com/nicolaskruchten/pivottable/issues/new and include a link to a CodePen or JSFiddle that shows the problem you're having please?

**Comment by mattmezs** [comment]
I figured out the issue. Thanks and great library!
