### ISSUE TITLE
Interoperability with Google Colab notebooks

### ISSUE THREAD

**Issue by tfproductanalysis** [nicolaskruchten/jupyter_pivottablejs#53]
Hi Nicolas,

Thank you for creating and maintaining this package! It's been super helpful for a project I've been working on.
When using pivot_ui() in a Jupyter notebook I haven't had any issues. However, I'm trying to get this to work in a Colab notebook as well. Unfortunately it returns the error "localhost refused to connect." I've tried this out with a variety of datasets to make sure that it isn't specific to the data.

Any suggestions or workarounds to get this function to work in Colab?

Thanks!

**Comment by nicolaskruchten** [comment]
Unfortunately the way this little wrapper works can only function with Jupyter and not other similar-looking notebooks :(

**Comment by tfproductanalysis** [comment]
Good to know. Thanks for the response!
