### ISSUE TITLE
A way to pass non JSON-serializable arguments in rendererOptions ?

### ISSUE THREAD

**Issue by Noctevent** [nicolaskruchten/jupyter_pivottablejs#62]
Hi !
I am trying to alter the name/value of the C3 tooltips generated in my graphs. This would be done by renderer option [tooltip.format.name](https://c3js.org/reference.html#tooltip-format-name). The C3 doc allows the use of a JS function that returns a formatted name. I have tried setting this option to different values (stringified JS function, string literal) and none have affected the way my tooltips show.
A great feature would be to be able to pass a Python callable, or a stringified JS function to drive those types of options. I have no idea if this is feasible without breaking your current implementation though. Cheers !

**Comment by nicolaskruchten** [comment]
It's unfortunately definitely not going to be possible :)

**Comment by Noctevent** [comment]
Yes I suspected your Python wrapper would be unable to do that by design, but it never hurts to ask ! Your library is already feature-rich as is, thanks for your answer. Cheers !
