### ISSUE TITLE
Jupyter Notebook Calling pivot_ui() Multiple Instances

### ISSUE THREAD

**Issue by yifeng021** [nicolaskruchten/jupyter_pivottablejs#65]
I am able to call pivot_ui() in Jupyter Notebook, and it works well.

What I want to do is to call pivot_ui() multiple times in a single notebook (may or may not be in the same cell). Each time pivot_ui() is called, I pass different input data into it, and I am hoping to get different pivot charts/tables, each reflecting its corresponding input data.

My example:  test1.csv and test2.csv are 2 different data files. I want to create pivot charts in a same notebook page, subsequently.
Here's my code:
![Code](https://user-images.githubusercontent.com/11248978/170519902-c4816e32-4701-41eb-a370-cf407c0361f2.PNG)

If I run the code for test1.csv only, the I get the chart below.
![test1](https://user-images.githubusercontent.com/11248978/170520540-25a3ed9e-43e4-48dd-abdc-fef50e77ee22.PNG)

If I run the code for test2.csv only, then I get the chart below.
![test2](https://user-images.githubusercontent.com/11248978/170520508-436c543b-9388-4112-b1a3-bfb8dac560d1.PNG)

However, if I 'Run All', then the pivot chart for test1.csv was overwritten with data from test2.csv.

Below are my 2 csv files.
[test1.csv](https://github.com/nicolaskruchten/jupyter_pivottablejs/files/8780114/test1.csv)
[test2.csv](https://github.com/nicolaskruchten/jupyter_pivottablejs/files/8780115/test2.csv)

Kindly advise if what I am hoping for is even possible. Thx!

Yifeng

**Comment by nicolaskruchten** [comment]
Every invocation of `pivot_ui()` writes a file to disk, and by default it's the same file path, so subsequent calls overwrite the same file. You can set the file path manually with the `outfile_path` keyword argument. If you set a different path for each call, you should be able to see multiple tables :)

**Comment by yifeng021** [comment]
I tried it and it works! Just like you said, so thank you.
In some other libraries, I may create a separate object for each invocation, and I create different copies of outputs that way. In this case, since I cannot find an object, I was actually kind of guessing you might have designed one of the input arguments to store a key that uniquely identify one particular invocation, but I wasn't able to figure out outfile_path is that 'key'. Thanks for helping me put 2 and 2 together.
