### ISSUE TITLE
TypeError: to_csv() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by dmd** [nicolaskruchten/jupyter_pivottablejs#7]
What am I doing wrong? I thought this would be pretty straightforward...

![screenshot_1447363530](https://cloud.githubusercontent.com/assets/41439/11131734/207a1dbe-895a-11e5-84b4-7e0b97b870ef.png)

**Comment by nicolaskruchten** [comment]
Most likely you are using a too-old version of Pandas, like in #1 ...
