### ISSUE TITLE
Support multiple aggregated columns

### ISSUE THREAD

**Issue by lev112** [nicolaskruchten/jupyter_pivottablejs#8]
It would be very useful to be able to choose more than 1 column to aggregate over
each column can have a different aggregation function

thanks

**Comment by nicolaskruchten** [comment]
Agreed. The underlying PivotTable.js library doesn't support that feature yet, but if and when it does, it will be neat to have it available in Jupyter also :)

**Comment by lev112** [comment]
thanks for your hard work
this looks great
