### ISSUE TITLE
Trips up with too much data

### ISSUE THREAD

**Issue by milesgranger** [nicolaskruchten/jupyter_pivottablejs#9]
This is fantastic, thanks! 

Perhaps it's a matter of not the right tool for the job, but I found this tends to fail with data which exceeds ~500,000 lines w/ >10 columns. Obviously the specific fail-point depends upon the client and dataframe content; but perhaps there is a way to cope with larger data sets? 

Thanks again!

**Comment by nicolaskruchten** [comment]
Glad you like it! This is definitely a question of "right tool for the job"... PivotTable.js (the underlying Javascript library) only gets decent performance up to around 100k records.
